# Generated by Django 4.0.4 on 2022-06-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_rename_pastes_paste'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='expire',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
